// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_nahE0Hes0ypZRmt4Ib0J1iNW57wGfM',
    appId: '1:467023206497:web:87c10c54efe4aadcb6b220',
    messagingSenderId: '467023206497',
    projectId: 'wms-gpsep',
    authDomain: 'wms-gpsep.firebaseapp.com',
    storageBucket: 'wms-gpsep.firebasestorage.app',
    measurementId: 'G-YR2T44GHT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqL-0sZVcdEv3ys9NPN25cjRorr3gadA',
    appId: '1:467023206497:android:e084f0fe4c7fa2d4b6b220',
    messagingSenderId: '467023206497',
    projectId: 'wms-gpsep',
    storageBucket: 'wms-gpsep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUpY1VQWg24ypDrTCn7MM2sSsbRaAeL9I',
    appId: '1:467023206497:ios:df0e6be00be67425b6b220',
    messagingSenderId: '467023206497',
    projectId: 'wms-gpsep',
    storageBucket: 'wms-gpsep.firebasestorage.app',
    iosBundleId: 'com.example.wms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUpY1VQWg24ypDrTCn7MM2sSsbRaAeL9I',
    appId: '1:467023206497:ios:df0e6be00be67425b6b220',
    messagingSenderId: '467023206497',
    projectId: 'wms-gpsep',
    storageBucket: 'wms-gpsep.firebasestorage.app',
    iosBundleId: 'com.example.wms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_nahE0Hes0ypZRmt4Ib0J1iNW57wGfM',
    appId: '1:467023206497:web:910243d647657765b6b220',
    messagingSenderId: '467023206497',
    projectId: 'wms-gpsep',
    authDomain: 'wms-gpsep.firebaseapp.com',
    storageBucket: 'wms-gpsep.firebasestorage.app',
    measurementId: 'G-EF3GVM3C16',
  );
}
